/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Frontend.Group;

import Backend.GroupManagament.Group;
import Backend.GroupManagament.GroupManager;
import javax.swing.JOptionPane;

/**
 *
 * @author carls
 */
public class PendingMembers extends javax.swing.JPanel {

    /**
     * Creates new form PendingMembers
     */
    private Group group;
    private GroupManager groupManager;
    private String userId;
    
    public PendingMembers(Group group, GroupManager groupManager, String userId) {
        
        initComponents();
        this.group = group;
        this.groupManager = groupManager;
        this.userId = userId;
        updatePendingMembers();
    }
    
    private void updatePendingMembers() {
        // Set the name and photo for the pending member
        PendingMemberNameField.setText(userId); // Set the name to the user's ID (replace with actual name if available)
        // PendingMemberPhotoLabel.setIcon(...); // Set the photo (replace with the user's photo if available)
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PendingMemberPhotoLabel = new javax.swing.JLabel();
        PendingMemberNameField = new javax.swing.JTextField();
        AcceptButton = new javax.swing.JButton();
        DeclineButton2 = new javax.swing.JButton();

        PendingMemberPhotoLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        PendingMemberNameField.setEditable(false);
        PendingMemberNameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PendingMemberNameFieldActionPerformed(evt);
            }
        });

        AcceptButton.setBackground(new java.awt.Color(51, 153, 255));
        AcceptButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        AcceptButton.setForeground(new java.awt.Color(255, 255, 255));
        AcceptButton.setText("Accept");
        AcceptButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AcceptButtonActionPerformed(evt);
            }
        });

        DeclineButton2.setBackground(new java.awt.Color(51, 153, 255));
        DeclineButton2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        DeclineButton2.setForeground(new java.awt.Color(255, 255, 255));
        DeclineButton2.setText("Decline");
        DeclineButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeclineButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(PendingMemberPhotoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(AcceptButton)
                        .addGap(18, 18, 18)
                        .addComponent(DeclineButton2))
                    .addComponent(PendingMemberNameField))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PendingMemberPhotoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(PendingMemberNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(AcceptButton)
                            .addComponent(DeclineButton2))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void AcceptButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AcceptButtonActionPerformed
        // TODO add your handling code here:
        if (group.isPendingRequest(userId)) {
            group.acceptMember(userId);
            JOptionPane.showMessageDialog(this, "Member accepted successfully!");
            updatePendingMembers(); // Refresh the list after accepting
        } else {
            JOptionPane.showMessageDialog(this, "This user is not in the pending list.");
        }
    }//GEN-LAST:event_AcceptButtonActionPerformed

    private void DeclineButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeclineButton2ActionPerformed
        // TODO add your handling code here:
        if (group.isPendingRequest(userId)) {
            group.declineMember(userId);
            JOptionPane.showMessageDialog(this, "Member declined.");
            updatePendingMembers(); // Refresh the list after declining
        } else {
            JOptionPane.showMessageDialog(this, "This user is not in the pending list.");
        }
    }//GEN-LAST:event_DeclineButton2ActionPerformed

    private void PendingMemberNameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PendingMemberNameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PendingMemberNameFieldActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AcceptButton;
    private javax.swing.JButton DeclineButton2;
    private javax.swing.JTextField PendingMemberNameField;
    private javax.swing.JLabel PendingMemberPhotoLabel;
    // End of variables declaration//GEN-END:variables
}
