/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Frontend;

import Backend.Manager;
import Frontend.GroupManagement.CreateGroup;
import java.awt.Image;
import java.io.File;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;


public class ProfileDetails extends javax.swing.JFrame {

    /**
     * Creates new form ProfileManagement
     */
    private String profilePath = ""; 
    private String coverPath = ""; 
    private Manager a;
    public ProfileDetails(Manager a) {
        initComponents();
        this.a = a;
        //making the bio text field not editable after pressing the button & editing it
        String profilePath = a.getProfilePhoto();
        ImageIcon imageIcon = new ImageIcon(profilePath);
            Image image = imageIcon.getImage().getScaledInstance(
                170, 
                170, 
                Image.SCALE_SMOOTH
            );
            profilePhoto.setIcon(new ImageIcon(image));
            profilePhoto.setText(""); 
        String coverPath = a.getCoverPhoto();
        ImageIcon imageIconC = new ImageIcon(coverPath);
        Image imageC = imageIconC.getImage().getScaledInstance(
                460, 
                220, 
                Image.SCALE_SMOOTH
            );
            coverPhoto.setIcon(new ImageIcon(imageC));
            coverPhoto.setText(""); 
            
        bioText.addFocusListener(new java.awt.event.FocusListener() {
        @Override
        public void focusGained(java.awt.event.FocusEvent e) {
            
        }

        @Override
        public void focusLost(java.awt.event.FocusEvent e) {
            
                bioText.setEditable(false);
                // put bio in the text field from appManager
            
        }
    });
       
      bioText.setText(a.getBio());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        profilePhoto = new javax.swing.JLabel();
        coverPhoto = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        bioText = new javax.swing.JTextField();
        editBio_btn = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        saveBio = new javax.swing.JButton();
        user_post_story = new javax.swing.JButton();
        CreateGroupButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        profilePhoto.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        coverPhoto.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jButton1.setBackground(new java.awt.Color(102, 153, 255));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Change Profile Photo");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(102, 153, 255));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Change Cover Photo");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("Bio");

        bioText.setEditable(false);
        bioText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bioTextActionPerformed(evt);
            }
        });

        editBio_btn.setBackground(new java.awt.Color(102, 153, 255));
        editBio_btn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        editBio_btn.setForeground(new java.awt.Color(255, 255, 255));
        editBio_btn.setText("Edit Bio");
        editBio_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editBio_btnActionPerformed(evt);
            }
        });

        saveBio.setBackground(new java.awt.Color(102, 153, 255));
        saveBio.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        saveBio.setForeground(new java.awt.Color(255, 255, 255));
        saveBio.setText("Save");
        saveBio.setEnabled(false);
        saveBio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBioActionPerformed(evt);
            }
        });

        user_post_story.setBackground(new java.awt.Color(102, 153, 255));
        user_post_story.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        user_post_story.setForeground(new java.awt.Color(255, 255, 255));
        user_post_story.setText("Show my posts and stories");
        user_post_story.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                user_post_storyActionPerformed(evt);
            }
        });

        CreateGroupButton.setBackground(new java.awt.Color(102, 153, 255));
        CreateGroupButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        CreateGroupButton.setForeground(new java.awt.Color(255, 255, 255));
        CreateGroupButton.setText("Create Group");
        CreateGroupButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreateGroupButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(profilePhoto, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jButton2)
                                    .addComponent(jButton1))))
                        .addGap(18, 18, 18)
                        .addComponent(coverPhoto, javax.swing.GroupLayout.PREFERRED_SIZE, 460, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(CreateGroupButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(user_post_story, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(editBio_btn)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(saveBio))
                        .addComponent(bioText, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(profilePhoto, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(coverPhoto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2)
                .addGap(21, 21, 21)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(bioText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(editBio_btn)
                    .addComponent(saveBio))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(user_post_story)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(CreateGroupButton)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        JFileChooser fileChooser = new JFileChooser();
        
        fileChooser.setFileFilter(new javax.swing.filechooser.FileFilter() {
            @Override
            public boolean accept(File file) {
                return file.isDirectory() || file.getName().toLowerCase().endsWith(".png");
            }

            @Override
            public String getDescription() {
                return "PNG Images (*.png)";
            }
        });
        
        int result = fileChooser.showOpenDialog(null);
        
        if (result == JFileChooser.APPROVE_OPTION) {
            File selectedFile = fileChooser.getSelectedFile();
             profilePath = selectedFile.getAbsolutePath();
             if(profilePath.endsWith(".png")){
            ImageIcon imageIcon = new ImageIcon(profilePath);
            Image image = imageIcon.getImage().getScaledInstance(
                profilePhoto.getWidth(), 
                profilePhoto.getHeight(), 
                Image.SCALE_SMOOTH
            );
            profilePhoto.setIcon(new ImageIcon(image));
            profilePhoto.setText(""); 
            
           JOptionPane.showMessageDialog(this, "photo uploaded successfully");
             }
             else{
             JOptionPane.showMessageDialog(null, "Selected file is not png image", "Warning", JOptionPane.WARNING_MESSAGE);
             }
        } else {
        JOptionPane.showMessageDialog(null, "No image selected", "Warning", JOptionPane.WARNING_MESSAGE);
        }
        
        a.changeProfilePhoto(profilePath);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        JFileChooser fileChooser = new JFileChooser();
        
        fileChooser.setFileFilter(new javax.swing.filechooser.FileFilter() {
            @Override
            public boolean accept(File file) {
                return file.isDirectory() || file.getName().toLowerCase().endsWith(".png");
            }

            @Override
            public String getDescription() {
                return "PNG Images (*.png)";
            }
        });
        
        // Show the file chooser dialog
        int result = fileChooser.showOpenDialog(null);
        
        // Check if the user selected a file
        if (result == JFileChooser.APPROVE_OPTION) {
            File selectedFile = fileChooser.getSelectedFile();
            coverPath = selectedFile.getAbsolutePath();
            if(coverPath.endsWith(".png")){
           ImageIcon imageIcon = new ImageIcon(coverPath);
            Image image = imageIcon.getImage().getScaledInstance(
                460, 
                220, 
                Image.SCALE_SMOOTH
            );
            coverPhoto.setIcon(new ImageIcon(image));
            coverPhoto.setText("");
            
           JOptionPane.showMessageDialog(this, "photo uploaded successfully");
            }
            else{
              JOptionPane.showMessageDialog(null, "Selected file is not png image", "Warning", JOptionPane.WARNING_MESSAGE);
            }
        } else {
        JOptionPane.showMessageDialog(null, "No image selected", "Warning", JOptionPane.WARNING_MESSAGE);
        }
       
        a.changeCoverPhoto(coverPath);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void bioTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bioTextActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_bioTextActionPerformed

    
    
    private void editBio_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editBio_btnActionPerformed
        // TODO add your handling code here:
        
        
        bioText.setEditable(true);
        bioText.setFocusable(true);
        saveBio.setEnabled(true);
        
        
    }//GEN-LAST:event_editBio_btnActionPerformed

    private void saveBioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBioActionPerformed
        // TODO add your handling code here:
        //Save in user bio
        
        bioText.setFocusable(false);
        saveBio.setEnabled(false);
        a.changeBio(bioText.getText());
        JOptionPane.showMessageDialog(ProfileDetails.this, "Bio saved successfully!");
    }//GEN-LAST:event_saveBioActionPerformed

    private void user_post_storyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_user_post_storyActionPerformed
        // TODO add your handling code here:
         JFrame frame = new JFrame("My Posts and Stories");
    frame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE); // Close on exit
    frame.setSize(800, 600); // Set the frame size
    frame.add(new PostsAndStories(a)); // Add your panel
    frame.setVisible(true); // Make the frame visible
        //new window for displaying user's post and stories
    }//GEN-LAST:event_user_post_storyActionPerformed

    private void CreateGroupButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreateGroupButtonActionPerformed
        // TODO add your handling code here:
        CreateGroup createGroup = new CreateGroup(a);
        createGroup.setVisible(true);
    }//GEN-LAST:event_CreateGroupButtonActionPerformed
    
    /*
    public static void main(String args[]) {

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
              //  new ProfileDetails(a).setVisible(true);
            }
        });
    }
*/

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CreateGroupButton;
    private javax.swing.JTextField bioText;
    private javax.swing.JLabel coverPhoto;
    private javax.swing.JButton editBio_btn;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel profilePhoto;
    private javax.swing.JButton saveBio;
    private javax.swing.JButton user_post_story;
    // End of variables declaration//GEN-END:variables
}
