/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Frontend;

import Backend.Manager;
import Backend.User;
import javax.swing.BoxLayout;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Lenovo
 */
public class searchResultPanel extends javax.swing.JPanel {

    /**
     * Creates new form searchResultPanel
     */
    private Manager manager;
    private User foundUser;

    public searchResultPanel(Manager manager, User foundUser) {
        this.manager = manager;
        this.foundUser = foundUser;
        initComponents(); // NetBeans GUI initialization
        setupResult(); // Custom method to display the result
    }

    private void setupResult() {
        if (foundUser != null) {
            // Display user details
            userLabel.setText("User Found: " + foundUser.getUserName());
            addFriendButton.setEnabled(true);
            removeFriendButton.setEnabled(true);
            blockUserButton.setEnabled(true);

        } else {
            // Display "No user found"
            userLabel.setText("No user found!");
            addFriendButton.setEnabled(false);
            removeFriendButton.setEnabled(false);
            blockUserButton.setEnabled(false);

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        userLabel = new javax.swing.JLabel();
        addFriendButton = new javax.swing.JButton();
        removeFriendButton = new javax.swing.JButton();
        blockUserButton = new javax.swing.JButton();

        userLabel.setText("jLabel1");

        addFriendButton.setText("Add Friend");
        addFriendButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addFriendButtonActionPerformed(evt);
            }
        });

        removeFriendButton.setText("Remove Friend");
        removeFriendButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeFriendButtonActionPerformed(evt);
            }
        });

        blockUserButton.setText("Block User");
        blockUserButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                blockUserButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(userLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(addFriendButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(blockUserButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(33, 33, 33)
                        .addComponent(removeFriendButton)))
                .addContainerGap(126, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(userLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addFriendButton)
                    .addComponent(removeFriendButton))
                .addGap(35, 35, 35)
                .addComponent(blockUserButton)
                .addContainerGap(99, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void addFriendButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addFriendButtonActionPerformed
        // TODO add your handling code here:
        if (manager.sendFriendRequest(foundUser.getUserId())) {
        JOptionPane.showMessageDialog(this, "Friend request sent to " + foundUser.getUserName());
    } else {
        JOptionPane.showMessageDialog(this, "Failed to send friend request!");
    }
    }//GEN-LAST:event_addFriendButtonActionPerformed

    private void removeFriendButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeFriendButtonActionPerformed
        // TODO add your handling code here:
        if (manager.cancelFriendRequest(foundUser.getUserId())) {
        JOptionPane.showMessageDialog(this, foundUser.getUserName() + " removed from your friends.");
    } else {
        JOptionPane.showMessageDialog(this, "Failed to remove friend!");
    }
    }//GEN-LAST:event_removeFriendButtonActionPerformed

    private void blockUserButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_blockUserButtonActionPerformed
        // TODO add your handling code here:
            if (manager.blockFriend(foundUser.getUserId())) {
        JOptionPane.showMessageDialog(this, foundUser.getUserName() + " has been blocked.");
    } else {
        JOptionPane.showMessageDialog(this, "Failed to block user!");
    }
    }//GEN-LAST:event_blockUserButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addFriendButton;
    private javax.swing.JButton blockUserButton;
    private javax.swing.JButton removeFriendButton;
    private javax.swing.JLabel userLabel;
    // End of variables declaration//GEN-END:variables
}
