/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Frontend.GroupManagement;

import java.awt.Image;
import java.io.File;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import Backend.Manager;


public class CreateGroup extends javax.swing.JFrame {

    /**
     * Creates new form CreateGroup
     */
    private String GroupPhoto = "";
    private String groupId = "";
    private Manager a;
    public CreateGroup(Manager a) {
        initComponents();
        this.a = a;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jNameField = new javax.swing.JTextField();
        DescriptionField = new javax.swing.JTextField();
        jPhotoLabel1 = new javax.swing.JLabel();
        UploadPhotoButton = new javax.swing.JButton();
        CreateGroupButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        DescriptionField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DescriptionFieldActionPerformed(evt);
            }
        });

        jPhotoLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jPhotoLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPhotoLabel1.setText("No Photo");

        UploadPhotoButton.setBackground(new java.awt.Color(102, 153, 255));
        UploadPhotoButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        UploadPhotoButton.setForeground(new java.awt.Color(255, 255, 255));
        UploadPhotoButton.setText("Upload photo");
        UploadPhotoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UploadPhotoButtonActionPerformed(evt);
            }
        });

        CreateGroupButton1.setBackground(new java.awt.Color(102, 153, 255));
        CreateGroupButton1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        CreateGroupButton1.setForeground(new java.awt.Color(255, 255, 255));
        CreateGroupButton1.setText("Create Group");
        CreateGroupButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreateGroupButton1ActionPerformed(evt);
            }
        });

        jLabel1.setText("Name");

        jLabel2.setText("Description");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(DescriptionField, javax.swing.GroupLayout.PREFERRED_SIZE, 383, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(UploadPhotoButton))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPhotoLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(91, 91, 91)
                                .addComponent(CreateGroupButton1)))
                        .addGap(190, 190, 190))))
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(DescriptionField, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jPhotoLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CreateGroupButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(UploadPhotoButton)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void DescriptionFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DescriptionFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DescriptionFieldActionPerformed

    private void CreateGroupButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreateGroupButton1ActionPerformed
        // TODO add your handling code here:
        String GroupName = jNameField.getText().trim();
        String Description= DescriptionField.getText().trim();
        if(GroupName.isEmpty() || Description.isEmpty()){
             JOptionPane.showMessageDialog(null, "there are empty fields.", "Warning", JOptionPane.WARNING_MESSAGE);
             return;
        }
         groupId = a.createGroup(GroupName);
         a.changeGroupDescription(Description, groupId);
        if(!GroupPhoto.isEmpty()){
             a.changeGroupPhoto(GroupPhoto,groupId);
             GroupPhoto = "";
             }
         JOptionPane.showMessageDialog(this, "Group created successfully");
         this.dispose();
    }//GEN-LAST:event_CreateGroupButton1ActionPerformed

    private void UploadPhotoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UploadPhotoButtonActionPerformed
        // TODO add your handling code here:
        JFileChooser fileChooser = new JFileChooser();
        
        fileChooser.setFileFilter(new javax.swing.filechooser.FileFilter() {
            @Override
            public boolean accept(File file) {
                return file.isDirectory() || file.getName().toLowerCase().endsWith(".png");
            }

            @Override
            public String getDescription() {
                return "PNG Images (*.png)";
            }
        });
        
        int result = fileChooser.showOpenDialog(null);
        
        if (result == JFileChooser.APPROVE_OPTION) {
            File selectedFile = fileChooser.getSelectedFile();
             GroupPhoto = selectedFile.getAbsolutePath();
             if(GroupPhoto.endsWith(".png")){
            ImageIcon imageIcon = new ImageIcon(GroupPhoto);
            Image image = imageIcon.getImage().getScaledInstance(
                jPhotoLabel1.getWidth(), 
                jPhotoLabel1.getHeight(), 
                Image.SCALE_SMOOTH
            );
            jPhotoLabel1.setIcon(new ImageIcon(image));
            jPhotoLabel1.setText(""); 
            
           JOptionPane.showMessageDialog(this, "photo uploaded successfully");
             }
             else{
             JOptionPane.showMessageDialog(null, "Selected file is not png image", "Warning", JOptionPane.WARNING_MESSAGE);
             }
        } else {
        JOptionPane.showMessageDialog(null, "No image selected", "Warning", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_UploadPhotoButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CreateGroupButton1;
    private javax.swing.JTextField DescriptionField;
    private javax.swing.JButton UploadPhotoButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField jNameField;
    private javax.swing.JLabel jPhotoLabel1;
    // End of variables declaration//GEN-END:variables
}
