/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Frontend.GroupManagement;

import Backend.Manager;
import Backend.PostString;
import java.util.ArrayList;

/**
 *
 * @author carls
 */
public class ManageGroupPosts extends javax.swing.JFrame {

    /**
     * Creates new form ManagePosts
     */
    Manager a;
    String gpId;
    public ManageGroupPosts(Manager a, String gpId) {
        initComponents();
        this.a=a;
        this.gpId= gpId;
        ArrayList<PostString> pendingPosts = a.getAllPendingPostsOfGroup(gpId);
        for(PostString p : pendingPosts){
            String text = p.getText();
            String date = p.getDate();
            String id= p.getPostId();
            String photo = p.getPhoto();
            String name  = p.getAuthor();
            if(photo.equals("No file selected")){
               PostTextForGroup gp = new PostTextForGroup(a, name, date, text, p.getPostId(), gpId);
               managePost.add(gp);
            }
            else{
                PostImageForGroup gp = new PostImageForGroup(a, name, photo, date, text, p.getPostId(), gpId);
                managePost.add(gp);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ManagePostsPane = new javax.swing.JScrollPane();
        managePost = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        managePost.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout managePostLayout = new javax.swing.GroupLayout(managePost);
        managePost.setLayout(managePostLayout);
        managePostLayout.setHorizontalGroup(
            managePostLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 683, Short.MAX_VALUE)
        );
        managePostLayout.setVerticalGroup(
            managePostLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 527, Short.MAX_VALUE)
        );

        ManagePostsPane.setViewportView(managePost);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(ManagePostsPane, javax.swing.GroupLayout.PREFERRED_SIZE, 685, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(92, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(ManagePostsPane, javax.swing.GroupLayout.PREFERRED_SIZE, 529, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane ManagePostsPane;
    private javax.swing.JPanel managePost;
    // End of variables declaration//GEN-END:variables
}
